"""empty message

Revision ID: 1c72b69ca82f
Revises: d9408fb79685
Create Date: 2019-09-08 01:30:10.999598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c72b69ca82f'
down_revision = 'd9408fb79685'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_assets():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_assets():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_connection():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_connection():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_recharge():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recharge_entry', 'mq_topup_datetime',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('recharge_entry', 'mq_topup_reference_id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('recharge_entry', 'mq_topup_status',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###


def downgrade_recharge():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recharge_entry', 'mq_topup_status',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('recharge_entry', 'mq_topup_reference_id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('recharge_entry', 'mq_topup_datetime',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###

