"""empty message

Revision ID: 360effe62bbe
Revises: 6d91e0c1adfa
Create Date: 2019-11-30 18:00:16.810695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '360effe62bbe'
down_revision = '6d91e0c1adfa'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_info', sa.Column('email_id', sa.String(length=100), nullable=True))
    op.add_column('customer_info', sa.Column('using_wishtalk', sa.String(length=3), nullable=False))
    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_info', 'zone_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('customer_info', 'user_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('customer_info', 'ip_addr',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('customer_info', 'customer_no',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('customer_info', 'customer_name',
               existing_type=mysql.VARCHAR(length=400),
               nullable=True)
    op.drop_column('customer_info', 'using_wishtalk')
    op.drop_column('customer_info', 'email_id')
    # ### end Alembic commands ###


def upgrade_assets():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_assets():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_connection():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_connection():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_recharge():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_recharge():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_ticket():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_ticket():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_softphone():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_softphone():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_series',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('series_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cat_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('tbl_series_master',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('series_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('series_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('series_frm', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('series_to', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cat_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('series_numbers', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('tot_numb', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('tbl_category',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('cat_id', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('cat_name', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('soft_price', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('ott_price', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    op.create_table('tab_soft',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('cust_no', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('cust_name', mysql.VARCHAR(length=10000), nullable=True),
    sa.Column('cust_mob', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('cust_pack', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('cust_max', mysql.INTEGER(display_width=10), autoincrement=False, nullable=True),
    sa.Column('cust_soft_no', mysql.INTEGER(display_width=10), autoincrement=False, nullable=True),
    sa.Column('rem_soft_no', mysql.INTEGER(display_width=10), autoincrement=False, nullable=False),
    sa.Column('cust_soft_nums', mysql.VARCHAR(length=2000), nullable=True),
    sa.Column('sf_no', mysql.INTEGER(display_width=10), autoincrement=False, nullable=True),
    sa.Column('pass', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('soft_os', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('create_dt', sa.DATE(), nullable=True),
    sa.Column('expiry_dt', sa.DATE(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    # ### end Alembic commands ###


def upgrade_voucher():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_voucher():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

