"""empty message

Revision ID: 6a2cae65abed
Revises: e846d70a1b06
Create Date: 2019-08-18 22:21:24.702229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a2cae65abed'
down_revision = 'e846d70a1b06'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'roles_users', 'role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'roles_users', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    # ### end Alembic commands ###


def upgrade_assets():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biz_plan', sa.Column('contention_ratio', sa.String(length=5), nullable=False))
    op.add_column('biz_plan', sa.Column('static_ip', sa.Integer(), nullable=False))
    op.add_column('ftth_plan', sa.Column('contention_ratio', sa.String(length=5), nullable=False))
    op.add_column('fup_plan', sa.Column('contention_ratio', sa.String(length=5), nullable=False))
    op.add_column('unlimited_plan', sa.Column('contention_ratio', sa.String(length=5), nullable=False))
    # ### end Alembic commands ###


def downgrade_assets():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unlimited_plan', 'contention_ratio')
    op.drop_column('fup_plan', 'contention_ratio')
    op.drop_column('ftth_plan', 'contention_ratio')
    op.drop_column('biz_plan', 'static_ip')
    op.drop_column('biz_plan', 'contention_ratio')
    # ### end Alembic commands ###


def upgrade_connection():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_connection():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

