"""empty message

Revision ID: 6d91e0c1adfa
Revises: 687abb721913
Create Date: 2019-11-30 09:51:46.821398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d91e0c1adfa'
down_revision = '687abb721913'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_info', sa.Column('ott_limit', sa.Integer(), nullable=True))
    op.add_column('customer_info', sa.Column('package', sa.String(length=100), nullable=True))
    op.add_column('customer_info', sa.Column('soft_limit', sa.Integer(), nullable=True))
    op.add_column('customer_info', sa.Column('zone_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_info', 'zone_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('customer_info', 'user_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('customer_info', 'ip_addr',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('customer_info', 'customer_no',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('customer_info', 'customer_name',
               existing_type=mysql.VARCHAR(length=400),
               nullable=True)
    op.drop_column('customer_info', 'zone_name')
    op.drop_column('customer_info', 'soft_limit')
    op.drop_column('customer_info', 'package')
    op.drop_column('customer_info', 'ott_limit')
    # ### end Alembic commands ###


def upgrade_assets():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_assets():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_connection():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_connection():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_recharge():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariff_info', sa.Column('ott', sa.Integer(), nullable=True))
    op.add_column('tariff_info', sa.Column('softphone', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade_recharge():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tariff_info', 'softphone')
    op.drop_column('tariff_info', 'ott')
    # ### end Alembic commands ###


def upgrade_ticket():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_ticket():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_softphone():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_series')
    op.drop_table('tab_soft')
    op.drop_table('tbl_categrory')
    op.drop_table('tbl_series_master')
    # ### end Alembic commands ###


def downgrade_softphone():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_series_master',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('series_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('series_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('series_frm', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('series_to', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cat_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('series_numbers', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('tot_numb', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('tbl_categrory',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('cat_id', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('cat_name', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('soft_price', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('ott_price', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    op.create_table('tab_soft',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('cust_no', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('cust_name', mysql.VARCHAR(length=10000), nullable=True),
    sa.Column('cust_mob', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('cust_pack', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('cust_max', mysql.INTEGER(display_width=10), autoincrement=False, nullable=True),
    sa.Column('cust_soft_no', mysql.INTEGER(display_width=10), autoincrement=False, nullable=True),
    sa.Column('rem_soft_no', mysql.INTEGER(display_width=10), autoincrement=False, nullable=False),
    sa.Column('cust_soft_nums', mysql.VARCHAR(length=2000), nullable=True),
    sa.Column('sf_no', mysql.INTEGER(display_width=10), autoincrement=False, nullable=True),
    sa.Column('pass', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('soft_os', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('create_dt', sa.DATE(), nullable=True),
    sa.Column('expiry_dt', sa.DATE(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=1000), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    op.create_table('tbl_series',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('series_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cat_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=1000), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def upgrade_voucher():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_voucher():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

