"""empty message

Revision ID: d7ec20329f29
Revises: b952f2b8c1d9
Create Date: 2019-09-10 00:08:10.907926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7ec20329f29'
down_revision = 'b952f2b8c1d9'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_assets():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_assets():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_connection():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_connection():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_recharge():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recharge_entry', sa.Column('payment_amount', sa.String(length=10), nullable=False))
    op.add_column('recharge_entry', sa.Column('refund_amount', sa.String(length=10), nullable=True))
    op.add_column('recharge_entry', sa.Column('refund_datetime', sa.String(length=50), nullable=True))
    op.add_column('recharge_entry', sa.Column('refund_status', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade_recharge():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recharge_entry', 'refund_status')
    op.drop_column('recharge_entry', 'refund_datetime')
    op.drop_column('recharge_entry', 'refund_amount')
    op.drop_column('recharge_entry', 'payment_amount')
    # ### end Alembic commands ###

